global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<YOUR_EMAIL>'
  smtp_auth_username: '<YOUR_EMAIL>'
  smtp_auth_password: '<YOUR_GMAIL_APP_PASSWORD>'

route:
  receiver: email-alert

receivers:
  - name: email-alert
    email_configs:
      - to: '<RECEIVER_EMAIL>'
        send_resolved: true
